version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: fullstack3002mvp
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    depends_on:
      - db
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_TYPE: asymmetric
      SSL: 0
      AUTH_TYPE: token
      CONNECTION_STRING: mysql+mysqlconnector://root:${MYSQL_ROOT_PASSWORD}@db/fullstack3002mvp
    volumes:
      - static-data:/app/static
    depends_on:
      - db
volumes:
  db-data:
  static-data:

